title: Brian Muitiriri Mugo | Data Scientist
name: Brian Muitiriri Mugo
description: Actuarial Science graduate specializing in machine learning for real-world problems.
url: "https://mugobrian201.github.io"
remote_theme: mmistakes/minimal-mistakes@4.24.0
minimal_mistakes_skin: default  # Try "dark" or "contrast" for variety
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap
collections:
  projects:
    output: true
    permalink: /:collection/:path/
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
author:
  name: "Brian Muitiriri Mugo"
  avatar: "/assets/images/profile.jpg"  # Upload a photo later
  bio: "Data Scientist | Machine Learning Enthusiast | Nyahururu, Kenya"
  location: "Nyahururu, Kenya"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mugobrian201@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/brian-mugo-a76339370/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mugobrian201"
    - label: "Projects Repo"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mugobrian201/portfolio"
    - label: "Phone"
      icon: "fas fa-fw fa-phone"
      url: "tel:+254112310090"
  navbar_links:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Contact
    url: /contact/
